// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AccountConnector encapsulates what a platform administrator needs to
/// configure for users to connect to the service providers, which includes,
/// among other fields, the OAuth client ID, client secret, and authorization and
/// token endpoints.
public struct AccountConnector: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the accountConnector, in the format
  /// `projects/{project}/locations/{location}/accountConnectors/{account_connector_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the accountConnector was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the accountConnector was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Allows users to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Start OAuth flow by clicking on this URL.
  public var oauthStartUri: Swift.String = Swift.String()

  /// The AccountConnector config.
  public var accountConnectorConfig: AccountConnectorConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AccountConnector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccountConnector().with { $0.providerOauthConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let providerOauthConfig = CodingKeys(stringValue: "providerOauthConfig")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let etag = CodingKeys(stringValue: "etag")
    static let labels = CodingKeys(stringValue: "labels")
    static let oauthStartUri = CodingKeys(stringValue: "oauthStartUri")

    static let _knownKeys: Set<Swift.String> = [
      "providerOauthConfig",
      "name",
      "createTime",
      "updateTime",
      "annotations",
      "etag",
      "labels",
      "oauthStartUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oauthStartUri) {
      self.oauthStartUri = value
    }

    var accountConnectorConfig: AccountConnectorConfigOneOf? = nil
    let accountConnectorConfigCheckAndSet = {
      if accountConnectorConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'accountConnectorConfig'"))
      }
      accountConnectorConfig = $0
    }
    if let providerOauthConfig = try container.decodeIfPresent(
      ProviderOAuthConfig?.self, forKey: .providerOauthConfig)
    {
      try accountConnectorConfigCheckAndSet(.providerOauthConfig(providerOauthConfig))
    }
    self.accountConnectorConfig = accountConnectorConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.oauthStartUri, forKey: .oauthStartUri)

    if let choice = self.accountConnectorConfig {
      switch choice {
      case .providerOauthConfig(let value):
        try container.encode(value, forKey: .providerOauthConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The AccountConnector config.
  public enum AccountConnectorConfigOneOf: Codable, Equatable, Sendable {
    /// Optional. Provider OAuth config.
    indirect case providerOauthConfig(ProviderOAuthConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.AccountConnector"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
