// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The artifact config of the artifact that is deployed.
public struct ArtifactConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Immutable. The URI of the artifact that is deployed.
  /// e.g. `us-docker.pkg.dev/my-project/my-repo/image`.
  /// The URI does not include the tag / digest because it captures a lineage of
  /// artifacts.
  public var uri: Swift.String = Swift.String()

  /// The storage location of the artifact.
  public var artifactStorage: OneOf_ArtifactStorage? = nil

  /// The storage location of the artifact metadata.
  public var artifactMetadataStorage: OneOf_ArtifactMetadataStorage? = nil

  /// Initialize a new instance of `ArtifactConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ArtifactConfig().with { $0.googleArtifactRegistry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case googleArtifactRegistry = "googleArtifactRegistry"
    case googleArtifactAnalysis = "googleArtifactAnalysis"
    case uri = "uri"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.uri = try container.decode(Swift.String.self, forKey: .uri)

    var artifactStorage: OneOf_ArtifactStorage? = nil
    let artifactStorageCheckAndSet = {
      if artifactStorage != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'artifactStorage'"))
      }
      artifactStorage = $0
    }
    if let googleArtifactRegistry = try container.decodeIfPresent(
      GoogleArtifactRegistry?.self, forKey: .googleArtifactRegistry)
    {
      try artifactStorageCheckAndSet(.googleArtifactRegistry(googleArtifactRegistry))
    }
    self.artifactStorage = artifactStorage

    var artifactMetadataStorage: OneOf_ArtifactMetadataStorage? = nil
    let artifactMetadataStorageCheckAndSet = {
      if artifactMetadataStorage != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'artifactMetadataStorage'"))
      }
      artifactMetadataStorage = $0
    }
    if let googleArtifactAnalysis = try container.decodeIfPresent(
      GoogleArtifactAnalysis?.self, forKey: .googleArtifactAnalysis)
    {
      try artifactMetadataStorageCheckAndSet(.googleArtifactAnalysis(googleArtifactAnalysis))
    }
    self.artifactMetadataStorage = artifactMetadataStorage
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)

    if let choice = self.artifactStorage {
      switch choice {
      case .googleArtifactRegistry(let value):
        try container.encode(value, forKey: .googleArtifactRegistry)
      }
    }

    if let choice = self.artifactMetadataStorage {
      switch choice {
      case .googleArtifactAnalysis(let value):
        try container.encode(value, forKey: .googleArtifactAnalysis)
      }
    }
  }

  /// The storage location of the artifact.
  public enum OneOf_ArtifactStorage: Codable, Equatable, Sendable {
    /// Optional. Set if the artifact is stored in Artifact registry.
    indirect case googleArtifactRegistry(GoogleArtifactRegistry?)
  }

  /// The storage location of the artifact metadata.
  public enum OneOf_ArtifactMetadataStorage: Codable, Equatable, Sendable {
    /// Optional. Set if the artifact metadata is stored in Artifact analysis.
    indirect case googleArtifactAnalysis(GoogleArtifactAnalysis?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.ArtifactConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
