// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The ArtifactDeployment resource represents the deployment of the artifact
/// within the InsightsConfig resource.
public struct ArtifactDeployment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Unique identifier of `ArtifactDeployment`.
  public var id: Swift.String = Swift.String()

  /// Output only. The artifact that is deployed.
  public var artifactReference: Swift.String = Swift.String()

  /// Output only. The artifact alias in the deployment spec, with Tag/SHA.
  /// e.g. us-docker.pkg.dev/my-project/my-repo/image:1.0.0
  public var artifactAlias: Swift.String = Swift.String()

  /// Output only. The source commits at which this artifact was built. Extracted
  /// from provenance.
  public var sourceCommitUris: [Swift.String] = []

  /// Output only. The time at which the deployment was deployed.
  public var deployTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the deployment was undeployed, all artifacts
  /// are considered undeployed once this time is set.
  public var undeployTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The summary of container status of the artifact deployment.
  /// Format as `ContainerStatusState-Reason : restartCount`
  /// e.g. "Waiting-ImagePullBackOff : 3"
  public var containerStatusSummary: Swift.String = Swift.String()

  /// Initialize a new instance of `ArtifactDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ArtifactDeployment().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.ArtifactDeployment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
