// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The DeploymentEvent resource represents the deployment of the artifact within
/// the InsightsConfig resource.
public struct DeploymentEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the DeploymentEvent. This name is provided by
  /// Developer Connect insights. Format:
  /// projects/{project}/locations/{location}/insightsConfigs/{insights_config}/deploymentEvents/{uuid}
  public var name: Swift.String = Swift.String()

  /// Output only. The create time of the DeploymentEvent.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The update time of the DeploymentEvent.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The runtime configurations where the DeploymentEvent happened.
  public var runtimeConfig: RuntimeConfig? = nil

  /// Output only. The runtime assigned URI of the DeploymentEvent.
  /// For GKE, this is the fully qualified replica set uri.
  /// e.g.
  /// container.googleapis.com/projects/{project}/locations/{location}/clusters/{cluster}/k8s/namespaces/{namespace}/apps/replicasets/{replica-set-id}
  /// For Cloud Run, this is the revision name.
  public var runtimeDeploymentUri: Swift.String = Swift.String()

  /// Output only. The state of the DeploymentEvent.
  public var state: DeploymentEvent.State = DeploymentEvent.State()

  /// Output only. The artifact deployments of the DeploymentEvent. Each artifact
  /// deployment contains the artifact uri and the runtime configuration uri. For
  /// GKE, this would be all the containers images that are deployed in the pod.
  public var artifactDeployments: [ArtifactDeployment] = []

  /// Output only. The time at which the DeploymentEvent was deployed.
  /// This would be the min of all ArtifactDeployment deploy_times.
  public var deployTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time at which the DeploymentEvent was undeployed, all
  /// artifacts are considered undeployed once this time is set. This would be
  /// the max of all ArtifactDeployment undeploy_times. If any ArtifactDeployment
  /// is still active (i.e. does not have an undeploy_time), this field will be
  /// empty.
  public var undeployTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `DeploymentEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeploymentEvent().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The state of the DeploymentEvent.
  public enum State: Codable, Equatable, Sendable {
    /// No state specified.
    case unspecified
    /// The deployment is active in the runtime.
    case active
    /// The deployment is not in the runtime.
    case inactive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "STATE_ACTIVE"
      case .inactive: return "STATE_INACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "STATE_ACTIVE": self = .active
      case "STATE_INACTIVE": self = .inactive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .inactive: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.DeploymentEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
