// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol DeveloperConnectStub {
    func listConnections(
      request: ListConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse

    func getConnection(
      request: GetConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.Connection

    func createConnection(
      request: CreateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateConnection(
      request: UpdateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createGitRepositoryLink(
      request: CreateGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteGitRepositoryLink(
      request: DeleteGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listGitRepositoryLinks(
      request: ListGitRepositoryLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse

    func getGitRepositoryLink(
      request: GetGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink

    func fetchReadWriteToken(
      request: FetchReadWriteTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse

    func fetchReadToken(
      request: FetchReadTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse

    func fetchLinkableGitRepositories(
      request: FetchLinkableGitRepositoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse

    func fetchGitHubInstallations(
      request: FetchGitHubInstallationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse

    func fetchGitRefs(
      request: FetchGitRefsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse

    func listAccountConnectors(
      request: ListAccountConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse

    func getAccountConnector(
      request: GetAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector

    func createAccountConnector(
      request: CreateAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateAccountConnector(
      request: UpdateAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAccountConnector(
      request: DeleteAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func fetchAccessToken(
      request: FetchAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse

    func listUsers(
      request: ListUsersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse

    func deleteUser(
      request: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func fetchSelf(
      request: FetchSelfRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.User

    func deleteSelf(
      request: DeleteSelfRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func startOauth(
      request: StartOAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse

    func finishOauth(
      request: FinishOAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
