// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class DeveloperConnectLogging: DeveloperConnectStub {
    let inner: any DeveloperConnectStub
    let logger: Logger

    public init(_ inner: any DeveloperConnectStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-developerconnect-v1"
      logger[metadataKey: "gcp.client.service"] = "developerconnect"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DeveloperConnect"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listConnections(
      request: ListConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnections",
        action: {
          (r: ListConnectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse
          in
          return try await self.inner.listConnections(request: r, options: o)
        })
    }

    public func getConnection(
      request: GetConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.Connection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnection",
        action: {
          (r: GetConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.Connection
          in
          return try await self.inner.getConnection(request: r, options: o)
        })
    }

    public func createConnection(
      request: CreateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConnection",
        action: {
          (r: CreateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnection(request: r, options: o)
        })
    }

    public func updateConnection(
      request: UpdateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConnection",
        action: {
          (r: UpdateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnection(request: r, options: o)
        })
    }

    public func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConnection",
        action: {
          (r: DeleteConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnection(request: r, options: o)
        })
    }

    public func createGitRepositoryLink(
      request: CreateGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createGitRepositoryLink",
        action: {
          (r: CreateGitRepositoryLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGitRepositoryLink(request: r, options: o)
        })
    }

    public func deleteGitRepositoryLink(
      request: DeleteGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteGitRepositoryLink",
        action: {
          (r: DeleteGitRepositoryLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGitRepositoryLink(request: r, options: o)
        })
    }

    public func listGitRepositoryLinks(
      request: ListGitRepositoryLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listGitRepositoryLinks",
        action: {
          (r: ListGitRepositoryLinksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse
          in
          return try await self.inner.listGitRepositoryLinks(request: r, options: o)
        })
    }

    public func getGitRepositoryLink(
      request: GetGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink {
      try await self._intercept(
        request: request,
        options: options,
        name: "getGitRepositoryLink",
        action: {
          (r: GetGitRepositoryLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.GitRepositoryLink
          in
          return try await self.inner.getGitRepositoryLink(request: r, options: o)
        })
    }

    public func fetchReadWriteToken(
      request: FetchReadWriteTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchReadWriteToken",
        action: {
          (r: FetchReadWriteTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse
          in
          return try await self.inner.fetchReadWriteToken(request: r, options: o)
        })
    }

    public func fetchReadToken(
      request: FetchReadTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchReadToken",
        action: {
          (r: FetchReadTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse
          in
          return try await self.inner.fetchReadToken(request: r, options: o)
        })
    }

    public func fetchLinkableGitRepositories(
      request: FetchLinkableGitRepositoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchLinkableGitRepositories",
        action: {
          (r: FetchLinkableGitRepositoriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse
          in
          return try await self.inner.fetchLinkableGitRepositories(request: r, options: o)
        })
    }

    public func fetchGitHubInstallations(
      request: FetchGitHubInstallationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchGitHubInstallations",
        action: {
          (r: FetchGitHubInstallationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse
          in
          return try await self.inner.fetchGitHubInstallations(request: r, options: o)
        })
    }

    public func fetchGitRefs(
      request: FetchGitRefsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchGitRefs",
        action: {
          (r: FetchGitRefsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse
          in
          return try await self.inner.fetchGitRefs(request: r, options: o)
        })
    }

    public func listAccountConnectors(
      request: ListAccountConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAccountConnectors",
        action: {
          (r: ListAccountConnectorsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse
          in
          return try await self.inner.listAccountConnectors(request: r, options: o)
        })
    }

    public func getAccountConnector(
      request: GetAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAccountConnector",
        action: {
          (r: GetAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.AccountConnector
          in
          return try await self.inner.getAccountConnector(request: r, options: o)
        })
    }

    public func createAccountConnector(
      request: CreateAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAccountConnector",
        action: {
          (r: CreateAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAccountConnector(request: r, options: o)
        })
    }

    public func updateAccountConnector(
      request: UpdateAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAccountConnector",
        action: {
          (r: UpdateAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAccountConnector(request: r, options: o)
        })
    }

    public func deleteAccountConnector(
      request: DeleteAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAccountConnector",
        action: {
          (r: DeleteAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAccountConnector(request: r, options: o)
        })
    }

    public func fetchAccessToken(
      request: FetchAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchAccessToken",
        action: {
          (r: FetchAccessTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse
          in
          return try await self.inner.fetchAccessToken(request: r, options: o)
        })
    }

    public func listUsers(
      request: ListUsersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listUsers",
        action: {
          (r: ListUsersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListUsersResponse
          in
          return try await self.inner.listUsers(request: r, options: o)
        })
    }

    public func deleteUser(
      request: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteUser",
        action: {
          (r: DeleteUserRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteUser(request: r, options: o)
        })
    }

    public func fetchSelf(
      request: FetchSelfRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.User {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchSelf",
        action: {
          (r: FetchSelfRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.User
          in
          return try await self.inner.fetchSelf(request: r, options: o)
        })
    }

    public func deleteSelf(
      request: DeleteSelfRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSelf",
        action: {
          (r: DeleteSelfRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSelf(request: r, options: o)
        })
    }

    public func startOauth(
      request: StartOAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "startOauth",
        action: {
          (r: StartOAuthRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.StartOAuthResponse
          in
          return try await self.inner.startOauth(request: r, options: o)
        })
    }

    public func finishOauth(
      request: FinishOAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "finishOauth",
        action: {
          (r: FinishOAuthRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse
          in
          return try await self.inner.finishOauth(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
