// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "DeveloperConnectQuickstart")
public final class DeveloperConnectClient: Clients.DeveloperConnectProtocol, Sendable {
  let inner: any Clients.DeveloperConnectStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `DeveloperConnectClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DeveloperConnectStub = try Clients.DeveloperConnectTransport(options)
    inner = Clients.DeveloperConnectRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DeveloperConnectLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Connections in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_ListConnections")
  public func listConnections(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse {
    try await self.inner.listConnections(request: request, options: options)
  }

  /// Gets details of a single Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_GetConnection")
  public func getConnection(
    request: GetConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.Connection {
    try await self.inner.getConnection(request: request, options: options)
  }

  /// Creates a new Connection in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_CreateConnection")
  public func createConnection(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnection(request: request, options: options)
  }

  /// Creates a new Connection in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_CreateConnection")
  public func createConnection(
    withPolling: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Connection>.State
      in
      return try op._extractStatus(Connection.self)
    }
    let rawOp = try await self.createConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_UpdateConnection")
  public func updateConnection(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConnection(request: request, options: options)
  }

  /// Updates the parameters of a single Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_UpdateConnection")
  public func updateConnection(
    withPolling: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Connection>.State
      in
      return try op._extractStatus(Connection.self)
    }
    let rawOp = try await self.updateConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteConnection")
  public func deleteConnection(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnection(request: request, options: options)
  }

  /// Deletes a single Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteConnection")
  public func deleteConnection(
    withPolling: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a GitRepositoryLink. Upon linking a Git Repository, Developer
  /// Connect will configure the Git Repository to send webhook events to
  /// Developer Connect. Connections that use Firebase GitHub Application will
  /// have events forwarded to the Firebase service. Connections that use Gemini
  /// Code Assist will have events forwarded to Gemini Code Assist service. All
  /// other Connections will have events forwarded to Cloud Build.
  ///
  /// @Snippet(path: "DeveloperConnect_CreateGitRepositoryLink")
  public func createGitRepositoryLink(
    request: CreateGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createGitRepositoryLink(request: request, options: options)
  }

  /// Creates a GitRepositoryLink. Upon linking a Git Repository, Developer
  /// Connect will configure the Git Repository to send webhook events to
  /// Developer Connect. Connections that use Firebase GitHub Application will
  /// have events forwarded to the Firebase service. Connections that use Gemini
  /// Code Assist will have events forwarded to Gemini Code Assist service. All
  /// other Connections will have events forwarded to Cloud Build.
  ///
  /// @Snippet(path: "DeveloperConnect_CreateGitRepositoryLink")
  public func createGitRepositoryLink(
    withPolling: CreateGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<GitRepositoryLink> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<GitRepositoryLink>.State in
      return try op._extractStatus(GitRepositoryLink.self)
    }
    let rawOp = try await self.createGitRepositoryLink(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<GitRepositoryLink>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single GitRepositoryLink.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteGitRepositoryLink")
  public func deleteGitRepositoryLink(
    request: DeleteGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteGitRepositoryLink(request: request, options: options)
  }

  /// Deletes a single GitRepositoryLink.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteGitRepositoryLink")
  public func deleteGitRepositoryLink(
    withPolling: DeleteGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteGitRepositoryLink(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists GitRepositoryLinks in a given project, location, and connection.
  ///
  /// @Snippet(path: "DeveloperConnect_ListGitRepositoryLinks")
  public func listGitRepositoryLinks(
    request: ListGitRepositoryLinksRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse {
    try await self.inner.listGitRepositoryLinks(request: request, options: options)
  }

  /// Gets details of a single GitRepositoryLink.
  ///
  /// @Snippet(path: "DeveloperConnect_GetGitRepositoryLink")
  public func getGitRepositoryLink(
    request: GetGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink {
    try await self.inner.getGitRepositoryLink(request: request, options: options)
  }

  /// Fetches read/write token of a given gitRepositoryLink.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchReadWriteToken")
  public func fetchReadWriteToken(
    request: FetchReadWriteTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse {
    try await self.inner.fetchReadWriteToken(request: request, options: options)
  }

  /// Fetches read token of a given gitRepositoryLink.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchReadToken")
  public func fetchReadToken(
    request: FetchReadTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse {
    try await self.inner.fetchReadToken(request: request, options: options)
  }

  /// FetchLinkableGitRepositories returns a list of git repositories from an SCM
  /// that are available to be added to a Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchLinkableGitRepositories")
  public func fetchLinkableGitRepositories(
    request: FetchLinkableGitRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse {
    try await self.inner.fetchLinkableGitRepositories(request: request, options: options)
  }

  /// FetchGitHubInstallations returns the list of GitHub Installations that
  /// are available to be added to a Connection.
  /// For github.com, only installations accessible to the authorizer token
  /// are returned. For GitHub Enterprise, all installations are returned.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchGitHubInstallations")
  public func fetchGitHubInstallations(
    request: FetchGitHubInstallationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse {
    try await self.inner.fetchGitHubInstallations(request: request, options: options)
  }

  /// Fetch the list of branches or tags for a given repository.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchGitRefs")
  public func fetchGitRefs(
    request: FetchGitRefsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse {
    try await self.inner.fetchGitRefs(request: request, options: options)
  }

  /// Lists AccountConnectors in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_ListAccountConnectors")
  public func listAccountConnectors(
    request: ListAccountConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse {
    try await self.inner.listAccountConnectors(request: request, options: options)
  }

  /// Gets details of a single AccountConnector.
  ///
  /// @Snippet(path: "DeveloperConnect_GetAccountConnector")
  public func getAccountConnector(
    request: GetAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector {
    try await self.inner.getAccountConnector(request: request, options: options)
  }

  /// Creates a new AccountConnector in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_CreateAccountConnector")
  public func createAccountConnector(
    request: CreateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAccountConnector(request: request, options: options)
  }

  /// Creates a new AccountConnector in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_CreateAccountConnector")
  public func createAccountConnector(
    withPolling: CreateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccountConnector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccountConnector>.State in
      return try op._extractStatus(AccountConnector.self)
    }
    let rawOp = try await self.createAccountConnector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccountConnector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single AccountConnector.
  ///
  /// @Snippet(path: "DeveloperConnect_UpdateAccountConnector")
  public func updateAccountConnector(
    request: UpdateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAccountConnector(request: request, options: options)
  }

  /// Updates the parameters of a single AccountConnector.
  ///
  /// @Snippet(path: "DeveloperConnect_UpdateAccountConnector")
  public func updateAccountConnector(
    withPolling: UpdateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccountConnector> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccountConnector>.State in
      return try op._extractStatus(AccountConnector.self)
    }
    let rawOp = try await self.updateAccountConnector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccountConnector>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single AccountConnector.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteAccountConnector")
  public func deleteAccountConnector(
    request: DeleteAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAccountConnector(request: request, options: options)
  }

  /// Deletes a single AccountConnector.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteAccountConnector")
  public func deleteAccountConnector(
    withPolling: DeleteAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAccountConnector(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Fetches OAuth access token based on end user credentials.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchAccessToken")
  public func fetchAccessToken(
    request: FetchAccessTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse {
    try await self.inner.fetchAccessToken(request: request, options: options)
  }

  /// Lists Users in a given project, location, and account_connector.
  ///
  /// @Snippet(path: "DeveloperConnect_ListUsers")
  public func listUsers(
    request: ListUsersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse {
    try await self.inner.listUsers(request: request, options: options)
  }

  /// Deletes a single User.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteUser")
  public func deleteUser(
    request: DeleteUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteUser(request: request, options: options)
  }

  /// Deletes a single User.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteUser")
  public func deleteUser(
    withPolling: DeleteUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteUser(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Fetch the User based on the user credentials.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchSelf")
  public func fetchSelf(
    request: FetchSelfRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.User {
    try await self.inner.fetchSelf(request: request, options: options)
  }

  /// Delete the User based on the user credentials.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteSelf")
  public func deleteSelf(
    request: DeleteSelfRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteSelf(request: request, options: options)
  }

  /// Delete the User based on the user credentials.
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteSelf")
  public func deleteSelf(
    withPolling: DeleteSelfRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteSelf(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Starts OAuth flow for an account connector.
  ///
  /// @Snippet(path: "DeveloperConnect_StartOAuth")
  public func startOauth(
    request: StartOAuthRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse {
    try await self.inner.startOauth(request: request, options: options)
  }

  /// Finishes OAuth flow for an account connector.
  ///
  /// @Snippet(path: "DeveloperConnect_FinishOAuth")
  public func finishOauth(
    request: FinishOAuthRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse {
    try await self.inner.finishOauth(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "DeveloperConnect_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "DeveloperConnect_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DeveloperConnect_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DeveloperConnect_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DeveloperConnect_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DeveloperConnect_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DeveloperConnectClient`.
  ///
  /// To mock `DeveloperConnectClient` change your functions to receive
  /// `some DeveloperConnectProtocol` or `any DeveloperConnectProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DeveloperConnectProtocol: Sendable {
    /// See `DeveloperConnectClient.createConnection`.
    func createConnection(withPolling: CreateConnectionRequest) async throws -> any GoogleGax
      .PollableOperation<Connection>

    /// See `DeveloperConnectClient.createConnection`.
    func createConnection(
      parent: Swift.String,
      connection: Connection?,
      connectionId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Connection>

    /// See `DeveloperConnectClient.updateConnection`.
    func updateConnection(withPolling: UpdateConnectionRequest) async throws -> any GoogleGax
      .PollableOperation<Connection>

    /// See `DeveloperConnectClient.updateConnection`.
    func updateConnection(
      connection: Connection?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Connection>

    /// See `DeveloperConnectClient.deleteConnection`.
    func deleteConnection(withPolling: DeleteConnectionRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.deleteConnection`.
    func deleteConnection(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.createGitRepositoryLink`.
    func createGitRepositoryLink(withPolling: CreateGitRepositoryLinkRequest) async throws
      -> any GoogleGax.PollableOperation<GitRepositoryLink>

    /// See `DeveloperConnectClient.createGitRepositoryLink`.
    func createGitRepositoryLink(
      parent: Swift.String,
      gitRepositoryLink: GitRepositoryLink?,
      gitRepositoryLinkId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<GitRepositoryLink>

    /// See `DeveloperConnectClient.deleteGitRepositoryLink`.
    func deleteGitRepositoryLink(withPolling: DeleteGitRepositoryLinkRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.deleteGitRepositoryLink`.
    func deleteGitRepositoryLink(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.createAccountConnector`.
    func createAccountConnector(withPolling: CreateAccountConnectorRequest) async throws
      -> any GoogleGax.PollableOperation<AccountConnector>

    /// See `DeveloperConnectClient.createAccountConnector`.
    func createAccountConnector(
      parent: Swift.String,
      accountConnector: AccountConnector?,
      accountConnectorId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<AccountConnector>

    /// See `DeveloperConnectClient.updateAccountConnector`.
    func updateAccountConnector(withPolling: UpdateAccountConnectorRequest) async throws
      -> any GoogleGax.PollableOperation<AccountConnector>

    /// See `DeveloperConnectClient.updateAccountConnector`.
    func updateAccountConnector(
      accountConnector: AccountConnector?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<AccountConnector>

    /// See `DeveloperConnectClient.deleteAccountConnector`.
    func deleteAccountConnector(withPolling: DeleteAccountConnectorRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.deleteAccountConnector`.
    func deleteAccountConnector(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.deleteUser`.
    func deleteUser(withPolling: DeleteUserRequest) async throws -> any GoogleGax.PollableOperation<
      Swift.Void
    >

    /// See `DeveloperConnectClient.deleteUser`.
    func deleteUser(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.deleteSelf`.
    func deleteSelf(withPolling: DeleteSelfRequest) async throws -> any GoogleGax.PollableOperation<
      Swift.Void
    >

    /// See `DeveloperConnectClient.deleteSelf`.
    func deleteSelf(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.listConnections`.
    func listConnections(
      request: ListConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse

    /// See `DeveloperConnectClient.getConnection`.
    func getConnection(
      request: GetConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.Connection

    /// See `DeveloperConnectClient.createConnection`.
    func createConnection(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.createConnection`.
    func createConnection(
      withPolling: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Connection>

    /// See `DeveloperConnectClient.updateConnection`.
    func updateConnection(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.updateConnection`.
    func updateConnection(
      withPolling: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Connection>

    /// See `DeveloperConnectClient.deleteConnection`.
    func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.deleteConnection`.
    func deleteConnection(
      withPolling: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.createGitRepositoryLink`.
    func createGitRepositoryLink(
      request: CreateGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.createGitRepositoryLink`.
    func createGitRepositoryLink(
      withPolling: CreateGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GitRepositoryLink>

    /// See `DeveloperConnectClient.deleteGitRepositoryLink`.
    func deleteGitRepositoryLink(
      request: DeleteGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.deleteGitRepositoryLink`.
    func deleteGitRepositoryLink(
      withPolling: DeleteGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.listGitRepositoryLinks`.
    func listGitRepositoryLinks(
      request: ListGitRepositoryLinksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse

    /// See `DeveloperConnectClient.getGitRepositoryLink`.
    func getGitRepositoryLink(
      request: GetGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink

    /// See `DeveloperConnectClient.fetchReadWriteToken`.
    func fetchReadWriteToken(
      request: FetchReadWriteTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse

    /// See `DeveloperConnectClient.fetchReadToken`.
    func fetchReadToken(
      request: FetchReadTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse

    /// See `DeveloperConnectClient.fetchLinkableGitRepositories`.
    func fetchLinkableGitRepositories(
      request: FetchLinkableGitRepositoriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse

    /// See `DeveloperConnectClient.fetchGitHubInstallations`.
    func fetchGitHubInstallations(
      request: FetchGitHubInstallationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse

    /// See `DeveloperConnectClient.fetchGitRefs`.
    func fetchGitRefs(
      request: FetchGitRefsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse

    /// See `DeveloperConnectClient.listAccountConnectors`.
    func listAccountConnectors(
      request: ListAccountConnectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse

    /// See `DeveloperConnectClient.getAccountConnector`.
    func getAccountConnector(
      request: GetAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector

    /// See `DeveloperConnectClient.createAccountConnector`.
    func createAccountConnector(
      request: CreateAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.createAccountConnector`.
    func createAccountConnector(
      withPolling: CreateAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccountConnector>

    /// See `DeveloperConnectClient.updateAccountConnector`.
    func updateAccountConnector(
      request: UpdateAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.updateAccountConnector`.
    func updateAccountConnector(
      withPolling: UpdateAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccountConnector>

    /// See `DeveloperConnectClient.deleteAccountConnector`.
    func deleteAccountConnector(
      request: DeleteAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.deleteAccountConnector`.
    func deleteAccountConnector(
      withPolling: DeleteAccountConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.fetchAccessToken`.
    func fetchAccessToken(
      request: FetchAccessTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse

    /// See `DeveloperConnectClient.listUsers`.
    func listUsers(
      request: ListUsersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse

    /// See `DeveloperConnectClient.deleteUser`.
    func deleteUser(
      request: DeleteUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.deleteUser`.
    func deleteUser(
      withPolling: DeleteUserRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.fetchSelf`.
    func fetchSelf(
      request: FetchSelfRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.User

    /// See `DeveloperConnectClient.deleteSelf`.
    func deleteSelf(
      request: DeleteSelfRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeveloperConnectClient.deleteSelf`.
    func deleteSelf(
      withPolling: DeleteSelfRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DeveloperConnectClient.startOauth`.
    func startOauth(
      request: StartOAuthRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse

    /// See `DeveloperConnectClient.finishOauth`.
    func finishOauth(
      request: FinishOAuthRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse

    /// See `DeveloperConnectClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DeveloperConnectClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DeveloperConnectClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DeveloperConnectClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DeveloperConnectClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DeveloperConnectProtocol {
  public func listConnections(request: ListConnectionsRequest) async throws
    -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse
  {
    try await self.listConnections(request: request, options: .init())
  }

  public func listConnections(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConnections(
    byItem: ListConnectionsRequest
  ) -> any AsyncSequence<Connection, Swift.Error> {
    self.listConnections(byItem: byItem, options: .init())
  }

  /// Lists Connections in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_ListConnections")
  public func listConnections(
    byItem: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Connection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listConnections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnections(
    parent: Swift.String,
  ) -> any AsyncSequence<Connection, Swift.Error> {
    let request = ListConnectionsRequest().with {
      $0.parent = parent
    }
    return self.listConnections(byItem: request)
  }

  public func getConnection(request: GetConnectionRequest) async throws
    -> GoogleCloudDeveloperConnectV1.Connection
  {
    try await self.getConnection(request: request, options: .init())
  }

  public func getConnection(
    request: GetConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.Connection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnection(
    name: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.Connection {
    let request = GetConnectionRequest().with {
      $0.name = name
    }
    return try await self.getConnection(request: request)
  }

  public func createConnection(request: CreateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnection(request: request, options: .init())
  }

  public func createConnection(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createConnection(withPolling: CreateConnectionRequest) async throws -> any GoogleGax
    .PollableOperation<Connection>
  {
    try await self.createConnection(withPolling: withPolling, options: .init())
  }

  public func createConnection(
    withPolling: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConnection(
    parent: Swift.String,
    connection: Connection?,
    connectionId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let request = CreateConnectionRequest().with {
      $0.parent = parent
      $0.connection = connection
      $0.connectionId = connectionId
    }
    return try await self.createConnection(withPolling: request)
  }

  public func updateConnection(request: UpdateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConnection(request: request, options: .init())
  }

  public func updateConnection(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConnection(withPolling: UpdateConnectionRequest) async throws -> any GoogleGax
    .PollableOperation<Connection>
  {
    try await self.updateConnection(withPolling: withPolling, options: .init())
  }

  public func updateConnection(
    withPolling: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConnection(
    connection: Connection?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Connection> {
    let request = UpdateConnectionRequest().with {
      $0.connection = connection
      $0.updateMask = updateMask
    }
    return try await self.updateConnection(withPolling: request)
  }

  public func deleteConnection(request: DeleteConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnection(request: request, options: .init())
  }

  public func deleteConnection(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConnection(withPolling: DeleteConnectionRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteConnection(withPolling: withPolling, options: .init())
  }

  public func deleteConnection(
    withPolling: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnection(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteConnectionRequest().with {
      $0.name = name
    }
    return try await self.deleteConnection(withPolling: request)
  }

  public func createGitRepositoryLink(request: CreateGitRepositoryLinkRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createGitRepositoryLink(request: request, options: .init())
  }

  public func createGitRepositoryLink(
    request: CreateGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createGitRepositoryLink(withPolling: CreateGitRepositoryLinkRequest) async throws
    -> any GoogleGax.PollableOperation<GitRepositoryLink>
  {
    try await self.createGitRepositoryLink(withPolling: withPolling, options: .init())
  }

  public func createGitRepositoryLink(
    withPolling: CreateGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<GitRepositoryLink> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<GitRepositoryLink>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createGitRepositoryLink(
    parent: Swift.String,
    gitRepositoryLink: GitRepositoryLink?,
    gitRepositoryLinkId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<GitRepositoryLink> {
    let request = CreateGitRepositoryLinkRequest().with {
      $0.parent = parent
      $0.gitRepositoryLink = gitRepositoryLink
      $0.gitRepositoryLinkId = gitRepositoryLinkId
    }
    return try await self.createGitRepositoryLink(withPolling: request)
  }

  public func deleteGitRepositoryLink(request: DeleteGitRepositoryLinkRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteGitRepositoryLink(request: request, options: .init())
  }

  public func deleteGitRepositoryLink(
    request: DeleteGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteGitRepositoryLink(withPolling: DeleteGitRepositoryLinkRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteGitRepositoryLink(withPolling: withPolling, options: .init())
  }

  public func deleteGitRepositoryLink(
    withPolling: DeleteGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteGitRepositoryLink(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteGitRepositoryLinkRequest().with {
      $0.name = name
    }
    return try await self.deleteGitRepositoryLink(withPolling: request)
  }

  public func listGitRepositoryLinks(request: ListGitRepositoryLinksRequest) async throws
    -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse
  {
    try await self.listGitRepositoryLinks(request: request, options: .init())
  }

  public func listGitRepositoryLinks(
    request: ListGitRepositoryLinksRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listGitRepositoryLinks(
    byItem: ListGitRepositoryLinksRequest
  ) -> any AsyncSequence<GitRepositoryLink, Swift.Error> {
    self.listGitRepositoryLinks(byItem: byItem, options: .init())
  }

  /// Lists GitRepositoryLinks in a given project, location, and connection.
  ///
  /// @Snippet(path: "DeveloperConnect_ListGitRepositoryLinks")
  public func listGitRepositoryLinks(
    byItem: ListGitRepositoryLinksRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GitRepositoryLink, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listGitRepositoryLinks(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listGitRepositoryLinks(
    parent: Swift.String,
  ) -> any AsyncSequence<GitRepositoryLink, Swift.Error> {
    let request = ListGitRepositoryLinksRequest().with {
      $0.parent = parent
    }
    return self.listGitRepositoryLinks(byItem: request)
  }

  public func getGitRepositoryLink(request: GetGitRepositoryLinkRequest) async throws
    -> GoogleCloudDeveloperConnectV1.GitRepositoryLink
  {
    try await self.getGitRepositoryLink(request: request, options: .init())
  }

  public func getGitRepositoryLink(
    request: GetGitRepositoryLinkRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGitRepositoryLink(
    name: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink {
    let request = GetGitRepositoryLinkRequest().with {
      $0.name = name
    }
    return try await self.getGitRepositoryLink(request: request)
  }

  public func fetchReadWriteToken(request: FetchReadWriteTokenRequest) async throws
    -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse
  {
    try await self.fetchReadWriteToken(request: request, options: .init())
  }

  public func fetchReadWriteToken(
    request: FetchReadWriteTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchReadWriteToken(
    gitRepositoryLink: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse {
    let request = FetchReadWriteTokenRequest().with {
      $0.gitRepositoryLink = gitRepositoryLink
    }
    return try await self.fetchReadWriteToken(request: request)
  }

  public func fetchReadToken(request: FetchReadTokenRequest) async throws
    -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse
  {
    try await self.fetchReadToken(request: request, options: .init())
  }

  public func fetchReadToken(
    request: FetchReadTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchReadToken(
    gitRepositoryLink: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse {
    let request = FetchReadTokenRequest().with {
      $0.gitRepositoryLink = gitRepositoryLink
    }
    return try await self.fetchReadToken(request: request)
  }

  public func fetchLinkableGitRepositories(request: FetchLinkableGitRepositoriesRequest)
    async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse
  {
    try await self.fetchLinkableGitRepositories(request: request, options: .init())
  }

  public func fetchLinkableGitRepositories(
    request: FetchLinkableGitRepositoriesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchLinkableGitRepositories(
    byItem: FetchLinkableGitRepositoriesRequest
  ) -> any AsyncSequence<LinkableGitRepository, Swift.Error> {
    self.fetchLinkableGitRepositories(byItem: byItem, options: .init())
  }

  /// FetchLinkableGitRepositories returns a list of git repositories from an SCM
  /// that are available to be added to a Connection.
  ///
  /// @Snippet(path: "DeveloperConnect_FetchLinkableGitRepositories")
  public func fetchLinkableGitRepositories(
    byItem: FetchLinkableGitRepositoriesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<LinkableGitRepository, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.fetchLinkableGitRepositories(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func fetchLinkableGitRepositories(
    connection: Swift.String,
  ) -> any AsyncSequence<LinkableGitRepository, Swift.Error> {
    let request = FetchLinkableGitRepositoriesRequest().with {
      $0.connection = connection
    }
    return self.fetchLinkableGitRepositories(byItem: request)
  }

  public func fetchGitHubInstallations(request: FetchGitHubInstallationsRequest) async throws
    -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse
  {
    try await self.fetchGitHubInstallations(request: request, options: .init())
  }

  public func fetchGitHubInstallations(
    request: FetchGitHubInstallationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchGitHubInstallations(
    connection: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse {
    let request = FetchGitHubInstallationsRequest().with {
      $0.connection = connection
    }
    return try await self.fetchGitHubInstallations(request: request)
  }

  public func fetchGitRefs(request: FetchGitRefsRequest) async throws
    -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse
  {
    try await self.fetchGitRefs(request: request, options: .init())
  }

  public func fetchGitRefs(
    request: FetchGitRefsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchGitRefs(
    gitRepositoryLink: Swift.String,
    refType: FetchGitRefsRequest.RefType,
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse {
    let request = FetchGitRefsRequest().with {
      $0.gitRepositoryLink = gitRepositoryLink
      $0.refType = refType
    }
    return try await self.fetchGitRefs(request: request)
  }

  public func listAccountConnectors(request: ListAccountConnectorsRequest) async throws
    -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse
  {
    try await self.listAccountConnectors(request: request, options: .init())
  }

  public func listAccountConnectors(
    request: ListAccountConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAccountConnectors(
    byItem: ListAccountConnectorsRequest
  ) -> any AsyncSequence<AccountConnector, Swift.Error> {
    self.listAccountConnectors(byItem: byItem, options: .init())
  }

  /// Lists AccountConnectors in a given project and location.
  ///
  /// @Snippet(path: "DeveloperConnect_ListAccountConnectors")
  public func listAccountConnectors(
    byItem: ListAccountConnectorsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<AccountConnector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAccountConnectors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAccountConnectors(
    parent: Swift.String,
  ) -> any AsyncSequence<AccountConnector, Swift.Error> {
    let request = ListAccountConnectorsRequest().with {
      $0.parent = parent
    }
    return self.listAccountConnectors(byItem: request)
  }

  public func getAccountConnector(request: GetAccountConnectorRequest) async throws
    -> GoogleCloudDeveloperConnectV1.AccountConnector
  {
    try await self.getAccountConnector(request: request, options: .init())
  }

  public func getAccountConnector(
    request: GetAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAccountConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector {
    let request = GetAccountConnectorRequest().with {
      $0.name = name
    }
    return try await self.getAccountConnector(request: request)
  }

  public func createAccountConnector(request: CreateAccountConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAccountConnector(request: request, options: .init())
  }

  public func createAccountConnector(
    request: CreateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAccountConnector(withPolling: CreateAccountConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<AccountConnector>
  {
    try await self.createAccountConnector(withPolling: withPolling, options: .init())
  }

  public func createAccountConnector(
    withPolling: CreateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccountConnector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccountConnector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAccountConnector(
    parent: Swift.String,
    accountConnector: AccountConnector?,
    accountConnectorId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AccountConnector> {
    let request = CreateAccountConnectorRequest().with {
      $0.parent = parent
      $0.accountConnector = accountConnector
      $0.accountConnectorId = accountConnectorId
    }
    return try await self.createAccountConnector(withPolling: request)
  }

  public func updateAccountConnector(request: UpdateAccountConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAccountConnector(request: request, options: .init())
  }

  public func updateAccountConnector(
    request: UpdateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAccountConnector(withPolling: UpdateAccountConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<AccountConnector>
  {
    try await self.updateAccountConnector(withPolling: withPolling, options: .init())
  }

  public func updateAccountConnector(
    withPolling: UpdateAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccountConnector> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<AccountConnector>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAccountConnector(
    accountConnector: AccountConnector?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<AccountConnector> {
    let request = UpdateAccountConnectorRequest().with {
      $0.accountConnector = accountConnector
      $0.updateMask = updateMask
    }
    return try await self.updateAccountConnector(withPolling: request)
  }

  public func deleteAccountConnector(request: DeleteAccountConnectorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAccountConnector(request: request, options: .init())
  }

  public func deleteAccountConnector(
    request: DeleteAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAccountConnector(withPolling: DeleteAccountConnectorRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAccountConnector(withPolling: withPolling, options: .init())
  }

  public func deleteAccountConnector(
    withPolling: DeleteAccountConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccountConnector(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAccountConnectorRequest().with {
      $0.name = name
    }
    return try await self.deleteAccountConnector(withPolling: request)
  }

  public func fetchAccessToken(request: FetchAccessTokenRequest) async throws
    -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse
  {
    try await self.fetchAccessToken(request: request, options: .init())
  }

  public func fetchAccessToken(
    request: FetchAccessTokenRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchAccessToken(
    accountConnector: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse {
    let request = FetchAccessTokenRequest().with {
      $0.accountConnector = accountConnector
    }
    return try await self.fetchAccessToken(request: request)
  }

  public func listUsers(request: ListUsersRequest) async throws
    -> GoogleCloudDeveloperConnectV1.ListUsersResponse
  {
    try await self.listUsers(request: request, options: .init())
  }

  public func listUsers(
    request: ListUsersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listUsers(
    byItem: ListUsersRequest
  ) -> any AsyncSequence<User, Swift.Error> {
    self.listUsers(byItem: byItem, options: .init())
  }

  /// Lists Users in a given project, location, and account_connector.
  ///
  /// @Snippet(path: "DeveloperConnect_ListUsers")
  public func listUsers(
    byItem: ListUsersRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<User, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listUsers(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listUsers(
    parent: Swift.String,
  ) -> any AsyncSequence<User, Swift.Error> {
    let request = ListUsersRequest().with {
      $0.parent = parent
    }
    return self.listUsers(byItem: request)
  }

  public func deleteUser(request: DeleteUserRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteUser(request: request, options: .init())
  }

  public func deleteUser(
    request: DeleteUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteUser(withPolling: DeleteUserRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteUser(withPolling: withPolling, options: .init())
  }

  public func deleteUser(
    withPolling: DeleteUserRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteUser(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteUserRequest().with {
      $0.name = name
    }
    return try await self.deleteUser(withPolling: request)
  }

  public func fetchSelf(request: FetchSelfRequest) async throws
    -> GoogleCloudDeveloperConnectV1.User
  {
    try await self.fetchSelf(request: request, options: .init())
  }

  public func fetchSelf(
    request: FetchSelfRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.User {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchSelf(
    name: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.User {
    let request = FetchSelfRequest().with {
      $0.name = name
    }
    return try await self.fetchSelf(request: request)
  }

  public func deleteSelf(request: DeleteSelfRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteSelf(request: request, options: .init())
  }

  public func deleteSelf(
    request: DeleteSelfRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteSelf(withPolling: DeleteSelfRequest) async throws -> any GoogleGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteSelf(withPolling: withPolling, options: .init())
  }

  public func deleteSelf(
    withPolling: DeleteSelfRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteSelf(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteSelfRequest().with {
      $0.name = name
    }
    return try await self.deleteSelf(withPolling: request)
  }

  public func startOauth(request: StartOAuthRequest) async throws
    -> GoogleCloudDeveloperConnectV1.StartOAuthResponse
  {
    try await self.startOauth(request: request, options: .init())
  }

  public func startOauth(
    request: StartOAuthRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func startOauth(
    accountConnector: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse {
    let request = StartOAuthRequest().with {
      $0.accountConnector = accountConnector
    }
    return try await self.startOauth(request: request)
  }

  public func finishOauth(request: FinishOAuthRequest) async throws
    -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse
  {
    try await self.finishOauth(request: request, options: .init())
  }

  public func finishOauth(
    request: FinishOAuthRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func finishOauth(
    accountConnector: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse {
    let request = FinishOAuthRequest().with {
      $0.accountConnector = accountConnector
    }
    return try await self.finishOauth(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "DeveloperConnect_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DeveloperConnect_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
