// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class DeveloperConnectRetry: DeveloperConnectStub {
    let inner: any DeveloperConnectStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any DeveloperConnectStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listConnections(
      request: ListConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConnectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListConnectionsResponse
          in
          return try await self.inner.listConnections(request: r, options: o)
        })
    }

    public func getConnection(
      request: GetConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.Connection {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.Connection
          in
          return try await self.inner.getConnection(request: r, options: o)
        })
    }

    public func createConnection(
      request: CreateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnection(request: r, options: o)
        })
    }

    public func updateConnection(
      request: UpdateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnection(request: r, options: o)
        })
    }

    public func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnection(request: r, options: o)
        })
    }

    public func createGitRepositoryLink(
      request: CreateGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGitRepositoryLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGitRepositoryLink(request: r, options: o)
        })
    }

    public func deleteGitRepositoryLink(
      request: DeleteGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGitRepositoryLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGitRepositoryLink(request: r, options: o)
        })
    }

    public func listGitRepositoryLinks(
      request: ListGitRepositoryLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGitRepositoryLinksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListGitRepositoryLinksResponse
          in
          return try await self.inner.listGitRepositoryLinks(request: r, options: o)
        })
    }

    public func getGitRepositoryLink(
      request: GetGitRepositoryLinkRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.GitRepositoryLink {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGitRepositoryLinkRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.GitRepositoryLink
          in
          return try await self.inner.getGitRepositoryLink(request: r, options: o)
        })
    }

    public func fetchReadWriteToken(
      request: FetchReadWriteTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FetchReadWriteTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchReadWriteTokenResponse
          in
          return try await self.inner.fetchReadWriteToken(request: r, options: o)
        })
    }

    public func fetchReadToken(
      request: FetchReadTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FetchReadTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchReadTokenResponse
          in
          return try await self.inner.fetchReadToken(request: r, options: o)
        })
    }

    public func fetchLinkableGitRepositories(
      request: FetchLinkableGitRepositoriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchLinkableGitRepositoriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchLinkableGitRepositoriesResponse
          in
          return try await self.inner.fetchLinkableGitRepositories(request: r, options: o)
        })
    }

    public func fetchGitHubInstallations(
      request: FetchGitHubInstallationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchGitHubInstallationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchGitHubInstallationsResponse
          in
          return try await self.inner.fetchGitHubInstallations(request: r, options: o)
        })
    }

    public func fetchGitRefs(
      request: FetchGitRefsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchGitRefsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchGitRefsResponse
          in
          return try await self.inner.fetchGitRefs(request: r, options: o)
        })
    }

    public func listAccountConnectors(
      request: ListAccountConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAccountConnectorsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListAccountConnectorsResponse
          in
          return try await self.inner.listAccountConnectors(request: r, options: o)
        })
    }

    public func getAccountConnector(
      request: GetAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.AccountConnector {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.AccountConnector
          in
          return try await self.inner.getAccountConnector(request: r, options: o)
        })
    }

    public func createAccountConnector(
      request: CreateAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAccountConnector(request: r, options: o)
        })
    }

    public func updateAccountConnector(
      request: UpdateAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAccountConnector(request: r, options: o)
        })
    }

    public func deleteAccountConnector(
      request: DeleteAccountConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAccountConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAccountConnector(request: r, options: o)
        })
    }

    public func fetchAccessToken(
      request: FetchAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: FetchAccessTokenRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FetchAccessTokenResponse
          in
          return try await self.inner.fetchAccessToken(request: r, options: o)
        })
    }

    public func listUsers(
      request: ListUsersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListUsersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListUsersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.ListUsersResponse
          in
          return try await self.inner.listUsers(request: r, options: o)
        })
    }

    public func deleteUser(
      request: DeleteUserRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteUserRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteUser(request: r, options: o)
        })
    }

    public func fetchSelf(
      request: FetchSelfRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.User {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FetchSelfRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.User
          in
          return try await self.inner.fetchSelf(request: r, options: o)
        })
    }

    public func deleteSelf(
      request: DeleteSelfRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSelfRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSelf(request: r, options: o)
        })
    }

    public func startOauth(
      request: StartOAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.StartOAuthResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: StartOAuthRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.StartOAuthResponse
          in
          return try await self.inner.startOauth(request: r, options: o)
        })
    }

    public func finishOauth(
      request: FinishOAuthRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: FinishOAuthRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDeveloperConnectV1.FinishOAuthResponse
          in
          return try await self.inner.finishOauth(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
