// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for finishing an OAuth flow.
public struct FinishOAuthRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the AccountConnector in the format
  /// `projects/*/locations/*/accountConnectors/*`.
  public var accountConnector: Swift.String = Swift.String()

  /// The params returned by OAuth flow redirect.
  public var params: OneOf_Params? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `FinishOAuthRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FinishOAuthRequest().with { $0.oauthParams = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let oauthParams = CodingKeys(stringValue: "oauthParams")
    static let googleOauthParams = CodingKeys(stringValue: "googleOauthParams")
    static let accountConnector = CodingKeys(stringValue: "accountConnector")

    static let _knownKeys: Set<Swift.String> = [
      "oauthParams",
      "googleOauthParams",
      "accountConnector",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accountConnector) {
      self.accountConnector = value
    }

    var params: OneOf_Params? = nil
    let paramsCheckAndSet = {
      if params != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'params'"))
      }
      params = $0
    }
    if let oauthParams = try container.decodeIfPresent(
      FinishOAuthRequest.OAuthParams?.self, forKey: .oauthParams)
    {
      try paramsCheckAndSet(.oauthParams(oauthParams))
    }
    if let googleOauthParams = try container.decodeIfPresent(
      FinishOAuthRequest.GoogleOAuthParams?.self, forKey: .googleOauthParams)
    {
      try paramsCheckAndSet(.googleOauthParams(googleOauthParams))
    }
    self.params = params
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accountConnector, forKey: .accountConnector)

    if let choice = self.params {
      switch choice {
      case .oauthParams(let value):
        try container.encode(value, forKey: .oauthParams)
      case .googleOauthParams(let value):
        try container.encode(value, forKey: .googleOauthParams)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The params returned by non-Google OAuth 2.0 flow redirect.
  public struct OAuthParams: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The code to be used for getting the token from SCM provider.
    public var code: Swift.String = Swift.String()

    /// Required. The ticket to be used for post processing the callback from SCM
    /// provider.
    public var ticket: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `OAuthParams`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = OAuthParams().with { $0.code = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let code = CodingKeys(stringValue: "code")
      static let ticket = CodingKeys(stringValue: "ticket")

      static let _knownKeys: Set<Swift.String> = [
        "code",
        "ticket",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .code) {
        self.code = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ticket) {
        self.ticket = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.code, forKey: .code)
      try container.encode(self.ticket, forKey: .ticket)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.developerconnect.v1.FinishOAuthRequest.OAuthParams"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The params returned by Google OAuth flow redirects.
  public struct GoogleOAuthParams: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The scopes returned by Google OAuth flow.
    public var scopes: [Swift.String] = []

    /// Optional. The version info returned by Google OAuth flow.
    public var versionInfo: Swift.String = Swift.String()

    /// Required. The ticket to be used for post processing the callback from
    /// Google OAuth flow.
    public var ticket: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `GoogleOAuthParams`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GoogleOAuthParams().with { $0.scopes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let scopes = CodingKeys(stringValue: "scopes")
      static let versionInfo = CodingKeys(stringValue: "versionInfo")
      static let ticket = CodingKeys(stringValue: "ticket")

      static let _knownKeys: Set<Swift.String> = [
        "scopes",
        "versionInfo",
        "ticket",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .scopes) {
        self.scopes = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .versionInfo) {
        self.versionInfo = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ticket) {
        self.ticket = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.scopes, forKey: .scopes)
      try container.encode(self.versionInfo, forKey: .versionInfo)
      try container.encode(self.ticket, forKey: .ticket)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.developerconnect.v1.FinishOAuthRequest.GoogleOAuthParams"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The params returned by OAuth flow redirect.
  public enum OneOf_Params: Codable, Equatable, Sendable {
    /// The params returned by non-Google OAuth 2.0 flow redirect.
    indirect case oauthParams(FinishOAuthRequest.OAuthParams?)
    /// The params returned by Google OAuth flow redirects.
    indirect case googleOauthParams(FinishOAuthRequest.GoogleOAuthParams?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.FinishOAuthRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
