// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Defines the configuration for connections to an HTTP service provider.
public struct GenericHTTPEndpointConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. The service provider's https endpoint.
  public var hostUri: Swift.String = Swift.String()

  /// Optional. Configuration for using Service Directory to privately connect to
  /// a HTTP service provider. This should only be set if the Http service
  /// provider is hosted on-premises and not reachable by public internet. If
  /// this field is left empty, calls to the HTTP service provider will be made
  /// over the public internet.
  public var serviceDirectoryConfig: ServiceDirectoryConfig? = nil

  /// Optional. The SSL certificate to use for requests to the HTTP service
  /// provider.
  public var sslCaCertificate: Swift.String = Swift.String()

  /// The authentication mechanism to use for requests to the HTTP service
  /// provider.
  public var authentication: OneOf_Authentication? = nil

  /// Initialize a new instance of `GenericHTTPEndpointConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenericHTTPEndpointConfig().with { $0.basicAuthentication = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case basicAuthentication = "basicAuthentication"
    case bearerTokenAuthentication = "bearerTokenAuthentication"
    case hostUri = "hostUri"
    case serviceDirectoryConfig = "serviceDirectoryConfig"
    case sslCaCertificate = "sslCaCertificate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.hostUri = try container.decode(Swift.String.self, forKey: .hostUri)
    self.serviceDirectoryConfig = try container.decodeIfPresent(
      ServiceDirectoryConfig.self, forKey: .serviceDirectoryConfig)
    self.sslCaCertificate = try container.decode(Swift.String.self, forKey: .sslCaCertificate)

    var authentication: OneOf_Authentication? = nil
    let authenticationCheckAndSet = {
      if authentication != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authentication'"))
      }
      authentication = $0
    }
    if let basicAuthentication = try container.decodeIfPresent(
      GenericHTTPEndpointConfig.BasicAuthentication?.self, forKey: .basicAuthentication)
    {
      try authenticationCheckAndSet(.basicAuthentication(basicAuthentication))
    }
    if let bearerTokenAuthentication = try container.decodeIfPresent(
      GenericHTTPEndpointConfig.BearerTokenAuthentication?.self, forKey: .bearerTokenAuthentication)
    {
      try authenticationCheckAndSet(.bearerTokenAuthentication(bearerTokenAuthentication))
    }
    self.authentication = authentication
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostUri, forKey: .hostUri)
    try container.encode(self.serviceDirectoryConfig, forKey: .serviceDirectoryConfig)
    try container.encode(self.sslCaCertificate, forKey: .sslCaCertificate)

    if let choice = self.authentication {
      switch choice {
      case .basicAuthentication(let value):
        try container.encode(value, forKey: .basicAuthentication)
      case .bearerTokenAuthentication(let value):
        try container.encode(value, forKey: .bearerTokenAuthentication)
      }
    }
  }

  /// Basic authentication with username and password.
  public struct BasicAuthentication: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The username to authenticate as.
    public var username: Swift.String = Swift.String()

    /// The password to authenticate as.
    public var password: OneOf_Password? = nil

    /// Initialize a new instance of `BasicAuthentication`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BasicAuthentication().with { $0.passwordSecretVersion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case passwordSecretVersion = "passwordSecretVersion"
      case username = "username"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.username = try container.decode(Swift.String.self, forKey: .username)

      var password: OneOf_Password? = nil
      let passwordCheckAndSet = {
        if password != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'password'"))
        }
        password = $0
      }
      if let passwordSecretVersion = try container.decodeIfPresent(
        Swift.String.self, forKey: .passwordSecretVersion)
      {
        try passwordCheckAndSet(.passwordSecretVersion(passwordSecretVersion))
      }
      self.password = password
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.username, forKey: .username)

      if let choice = self.password {
        switch choice {
        case .passwordSecretVersion(let value):
          try container.encode(value, forKey: .passwordSecretVersion)
        }
      }
    }

    /// The password to authenticate as.
    public enum OneOf_Password: Codable, Equatable, Sendable {
      /// The password SecretManager secret version to authenticate as.
      case passwordSecretVersion(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.developerconnect.v1.GenericHTTPEndpointConfig.BasicAuthentication"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Bearer token authentication with a token.
  public struct BearerTokenAuthentication: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The token to authenticate as.
    public var token: OneOf_Token? = nil

    /// Initialize a new instance of `BearerTokenAuthentication`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BearerTokenAuthentication().with { $0.tokenSecretVersion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case tokenSecretVersion = "tokenSecretVersion"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var token: OneOf_Token? = nil
      let tokenCheckAndSet = {
        if token != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'token'"))
        }
        token = $0
      }
      if let tokenSecretVersion = try container.decodeIfPresent(
        Swift.String.self, forKey: .tokenSecretVersion)
      {
        try tokenCheckAndSet(.tokenSecretVersion(tokenSecretVersion))
      }
      self.token = token
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.token {
        switch choice {
        case .tokenSecretVersion(let value):
          try container.encode(value, forKey: .tokenSecretVersion)
        }
      }
    }

    /// The token to authenticate as.
    public enum OneOf_Token: Codable, Equatable, Sendable {
      /// Optional. The token SecretManager secret version to authenticate as.
      case tokenSecretVersion(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.developerconnect.v1.GenericHTTPEndpointConfig.BearerTokenAuthentication"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The authentication mechanism to use for requests to the HTTP service
  /// provider.
  public enum OneOf_Authentication: Codable, Equatable, Sendable {
    /// Optional. Basic authentication with username and password.
    indirect case basicAuthentication(GenericHTTPEndpointConfig.BasicAuthentication?)
    /// Optional. Bearer token authentication with a token.
    indirect case bearerTokenAuthentication(GenericHTTPEndpointConfig.BearerTokenAuthentication?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.GenericHTTPEndpointConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
