// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration for connections to gitlab.com.
public struct GitLabConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Immutable. SecretManager resource containing the webhook secret
  /// of a GitLab project, formatted as `projects/*/secrets/*/versions/*` or
  /// `projects/*/locations/*/secrets/*/versions/*` (if regional secrets are
  /// supported in that location). This is used to validate webhooks.
  public var webhookSecretSecretVersion: Swift.String = Swift.String()

  /// Required. A GitLab personal access token with the minimum `read_api` scope
  /// access and a minimum role of `reporter`. The GitLab Projects visible to
  /// this Personal Access Token will control which Projects Developer Connect
  /// has access to.
  public var readAuthorizerCredential: UserCredential? = nil

  /// Required. A GitLab personal access token with the minimum `api` scope
  /// access and a minimum role of `maintainer`. The GitLab Projects visible to
  /// this Personal Access Token will control which Projects Developer Connect
  /// has access to.
  public var authorizerCredential: UserCredential? = nil

  /// Initialize a new instance of `GitLabConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitLabConfig().with { $0.webhookSecretSecretVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.GitLabConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
