// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing the GitRepositoryLink object
public struct GitRepositoryLink: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the repository, in the format
  /// `projects/*/locations/*/connections/*/gitRepositoryLinks/*`.
  public var name: Swift.String = Swift.String()

  /// Required. Git Clone URI.
  public var cloneUri: Swift.String = Swift.String()

  /// Output only. [Output only] Create timestamp
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. [Output only] Update timestamp
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. [Output only] Delete timestamp
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Set to true when the connection is being set up or updated in
  /// the background.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Allows clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. A system-assigned unique identifier for the GitRepositoryLink.
  public var uid: Swift.String = Swift.String()

  /// Output only. External ID of the webhook created for the repository.
  public var webhookId: Swift.String = Swift.String()

  /// Output only. URI to access the linked repository through the Git Proxy.
  /// This field is only populated if the git proxy is enabled for the
  /// connection.
  public var gitProxyUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GitRepositoryLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitRepositoryLink().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let cloneUri = CodingKeys(stringValue: "cloneUri")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let etag = CodingKeys(stringValue: "etag")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let uid = CodingKeys(stringValue: "uid")
    static let webhookId = CodingKeys(stringValue: "webhookId")
    static let gitProxyUri = CodingKeys(stringValue: "gitProxyUri")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "cloneUri",
      "createTime",
      "updateTime",
      "deleteTime",
      "labels",
      "etag",
      "reconciling",
      "annotations",
      "uid",
      "webhookId",
      "gitProxyUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloneUri) {
      self.cloneUri = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .webhookId) {
      self.webhookId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gitProxyUri) {
      self.gitProxyUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.cloneUri, forKey: .cloneUri)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.webhookId, forKey: .webhookId)
    try container.encode(self.gitProxyUri, forKey: .gitProxyUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.GitRepositoryLink"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
