// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Message describing the GitRepositoryLink object
public struct GitRepositoryLink: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the repository, in the format
  /// `projects/*/locations/*/connections/*/gitRepositoryLinks/*`.
  public var name: Swift.String = Swift.String()

  /// Required. Git Clone URI.
  public var cloneUri: Swift.String = Swift.String()

  /// Output only. [Output only] Create timestamp
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Update timestamp
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. [Output only] Delete timestamp
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Set to true when the connection is being set up or updated in
  /// the background.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. Allows clients to store small amounts of arbitrary data.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. A system-assigned unique identifier for the GitRepositoryLink.
  public var uid: Swift.String = Swift.String()

  /// Output only. External ID of the webhook created for the repository.
  public var webhookId: Swift.String = Swift.String()

  /// Output only. URI to access the linked repository through the Git Proxy.
  /// This field is only populated if the git proxy is enabled for the
  /// connection.
  public var gitProxyUri: Swift.String = Swift.String()

  /// Initialize a new instance of `GitRepositoryLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GitRepositoryLink().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.GitRepositoryLink"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
