// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Creates and manages InsightsConfigs.
///
/// The InsightsConfig resource is the core configuration object to capture
/// events from your Software Development Lifecycle. It acts as the central hub
/// for managing how Developer Connect understands your application, its runtime
/// environments, and the artifacts deployed within them.
/// A user can create an InsightsConfig, list previously-requested
/// InsightsConfigs or get InsightsConfigs by their ID to determine the status of
/// the InsightsConfig.
///
/// @Snippet(path: "InsightsConfigServiceQuickstart")
public class InsightsConfigServiceClient: Clients.InsightsConfigServiceProtocol {
  let inner: any Clients.InsightsConfigServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `InsightsConfigServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.InsightsConfigServiceStub = try Clients.InsightsConfigServiceTransport(
      options)
    inner = Clients.InsightsConfigServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.InsightsConfigServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists InsightsConfigs in a given project and location.
  ///
  /// @Snippet(path: "InsightsConfigService_ListInsightsConfigs")
  public func listInsightsConfigs(
    request: ListInsightsConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse {
    try await self.inner.listInsightsConfigs(request: request, options: options)
  }

  /// Lists InsightsConfigs in a given project and location.
  ///
  /// @Snippet(path: "InsightsConfigService_ListInsightsConfigs")
  public func listInsightsConfigs(
    byItem: ListInsightsConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<InsightsConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listInsightsConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new InsightsConfig in a given project and location.
  ///
  /// @Snippet(path: "InsightsConfigService_CreateInsightsConfig")
  public func createInsightsConfig(
    request: CreateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInsightsConfig(request: request, options: options)
  }

  /// Creates a new InsightsConfig in a given project and location.
  ///
  /// @Snippet(path: "InsightsConfigService_CreateInsightsConfig")
  public func createInsightsConfig(
    withPolling: CreateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<InsightsConfig>.State in
      return try op._extractStatus(InsightsConfig.self)
    }
    let rawOp = try await self.createInsightsConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InsightsConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets details of a single Insight.
  ///
  /// @Snippet(path: "InsightsConfigService_GetInsightsConfig")
  public func getInsightsConfig(
    request: GetInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.InsightsConfig {
    try await self.inner.getInsightsConfig(request: request, options: options)
  }

  /// Updates the parameters of a single InsightsConfig.
  ///
  /// @Snippet(path: "InsightsConfigService_UpdateInsightsConfig")
  public func updateInsightsConfig(
    request: UpdateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInsightsConfig(request: request, options: options)
  }

  /// Updates the parameters of a single InsightsConfig.
  ///
  /// @Snippet(path: "InsightsConfigService_UpdateInsightsConfig")
  public func updateInsightsConfig(
    withPolling: UpdateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<InsightsConfig>.State in
      return try op._extractStatus(InsightsConfig.self)
    }
    let rawOp = try await self.updateInsightsConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InsightsConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Insight.
  ///
  /// @Snippet(path: "InsightsConfigService_DeleteInsightsConfig")
  public func deleteInsightsConfig(
    request: DeleteInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInsightsConfig(request: request, options: options)
  }

  /// Deletes a single Insight.
  ///
  /// @Snippet(path: "InsightsConfigService_DeleteInsightsConfig")
  public func deleteInsightsConfig(
    withPolling: DeleteInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInsightsConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a single Deployment Event.
  ///
  /// @Snippet(path: "InsightsConfigService_GetDeploymentEvent")
  public func getDeploymentEvent(
    request: GetDeploymentEventRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.DeploymentEvent {
    try await self.inner.getDeploymentEvent(request: request, options: options)
  }

  /// Lists Deployment Events in a given insights config.
  ///
  /// @Snippet(path: "InsightsConfigService_ListDeploymentEvents")
  public func listDeploymentEvents(
    request: ListDeploymentEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse {
    try await self.inner.listDeploymentEvents(request: request, options: options)
  }

  /// Lists Deployment Events in a given insights config.
  ///
  /// @Snippet(path: "InsightsConfigService_ListDeploymentEvents")
  public func listDeploymentEvents(
    byItem: ListDeploymentEventsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDeploymentEvents(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "InsightsConfigService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "InsightsConfigService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "InsightsConfigService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InsightsConfigService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InsightsConfigService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InsightsConfigService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InsightsConfigService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "InsightsConfigService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `InsightsConfigServiceClient`.
  ///
  /// To mock `InsightsConfigServiceClient` change your functions to receive
  /// `some InsightsConfigServiceProtocol` or `any InsightsConfigServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol InsightsConfigServiceProtocol {
    /// See `InsightsConfigServiceClient.listInsightsConfigs`.
    func listInsightsConfigs(request: ListInsightsConfigsRequest) async throws
      -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse

    /// See `InsightsConfigServiceClient.listInsightsConfigs`.
    func listInsightsConfigs(
      byItem: ListInsightsConfigsRequest
    ) throws -> any AsyncSequence<InsightsConfig, Swift.Error>

    /// See `InsightsConfigServiceClient.listInsightsConfigs`.
    func listInsightsConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<InsightsConfig, Swift.Error>

    /// See `InsightsConfigServiceClient.createInsightsConfig`.
    func createInsightsConfig(request: CreateInsightsConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `InsightsConfigServiceClient.createInsightsConfig`.
    func createInsightsConfig(withPolling: CreateInsightsConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<InsightsConfig>

    /// See `InsightsConfigServiceClient.createInsightsConfig`.
    func createInsightsConfig(
      parent: Swift.String,
      insightsConfig: InsightsConfig?,
      insightsConfigId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig>

    /// See `InsightsConfigServiceClient.getInsightsConfig`.
    func getInsightsConfig(request: GetInsightsConfigRequest) async throws
      -> GoogleCloudDeveloperConnectV1.InsightsConfig

    /// See `InsightsConfigServiceClient.getInsightsConfig`.
    func getInsightsConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudDeveloperConnectV1.InsightsConfig

    /// See `InsightsConfigServiceClient.updateInsightsConfig`.
    func updateInsightsConfig(request: UpdateInsightsConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `InsightsConfigServiceClient.updateInsightsConfig`.
    func updateInsightsConfig(withPolling: UpdateInsightsConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<InsightsConfig>

    /// See `InsightsConfigServiceClient.deleteInsightsConfig`.
    func deleteInsightsConfig(request: DeleteInsightsConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `InsightsConfigServiceClient.deleteInsightsConfig`.
    func deleteInsightsConfig(withPolling: DeleteInsightsConfigRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `InsightsConfigServiceClient.deleteInsightsConfig`.
    func deleteInsightsConfig(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `InsightsConfigServiceClient.getDeploymentEvent`.
    func getDeploymentEvent(request: GetDeploymentEventRequest) async throws
      -> GoogleCloudDeveloperConnectV1.DeploymentEvent

    /// See `InsightsConfigServiceClient.getDeploymentEvent`.
    func getDeploymentEvent(
      name: Swift.String,
    ) async throws -> GoogleCloudDeveloperConnectV1.DeploymentEvent

    /// See `InsightsConfigServiceClient.listDeploymentEvents`.
    func listDeploymentEvents(request: ListDeploymentEventsRequest) async throws
      -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse

    /// See `InsightsConfigServiceClient.listDeploymentEvents`.
    func listDeploymentEvents(
      byItem: ListDeploymentEventsRequest
    ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error>

    /// See `InsightsConfigServiceClient.listDeploymentEvents`.
    func listDeploymentEvents(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error>

    /// See `InsightsConfigServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `InsightsConfigServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `InsightsConfigServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `InsightsConfigServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `InsightsConfigServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `InsightsConfigServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `InsightsConfigServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `InsightsConfigServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `InsightsConfigServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `InsightsConfigServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `InsightsConfigServiceClient.listInsightsConfigs`.
    func listInsightsConfigs(
      request: ListInsightsConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse

    /// See `InsightsConfigServiceClient.listInsightsConfigs`.
    func listInsightsConfigs(
      byItem: ListInsightsConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<InsightsConfig, Swift.Error>

    /// See `InsightsConfigServiceClient.createInsightsConfig`.
    func createInsightsConfig(
      request: CreateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InsightsConfigServiceClient.createInsightsConfig`.
    func createInsightsConfig(
      withPolling: CreateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig>

    /// See `InsightsConfigServiceClient.getInsightsConfig`.
    func getInsightsConfig(
      request: GetInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.InsightsConfig

    /// See `InsightsConfigServiceClient.updateInsightsConfig`.
    func updateInsightsConfig(
      request: UpdateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InsightsConfigServiceClient.updateInsightsConfig`.
    func updateInsightsConfig(
      withPolling: UpdateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig>

    /// See `InsightsConfigServiceClient.deleteInsightsConfig`.
    func deleteInsightsConfig(
      request: DeleteInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `InsightsConfigServiceClient.deleteInsightsConfig`.
    func deleteInsightsConfig(
      withPolling: DeleteInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `InsightsConfigServiceClient.getDeploymentEvent`.
    func getDeploymentEvent(
      request: GetDeploymentEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.DeploymentEvent

    /// See `InsightsConfigServiceClient.listDeploymentEvents`.
    func listDeploymentEvents(
      request: ListDeploymentEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse

    /// See `InsightsConfigServiceClient.listDeploymentEvents`.
    func listDeploymentEvents(
      byItem: ListDeploymentEventsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error>

    /// See `InsightsConfigServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `InsightsConfigServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `InsightsConfigServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `InsightsConfigServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `InsightsConfigServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `InsightsConfigServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `InsightsConfigServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.InsightsConfigServiceProtocol {
  public func listInsightsConfigs(request: ListInsightsConfigsRequest) async throws
    -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse
  {
    try await self.listInsightsConfigs(request: request, options: .init())
  }

  public func listInsightsConfigs(
    request: ListInsightsConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listInsightsConfigs(
    byItem: ListInsightsConfigsRequest
  ) throws -> any AsyncSequence<InsightsConfig, Swift.Error> {
    try self.listInsightsConfigs(byItem: byItem, options: .init())
  }

  public func listInsightsConfigs(
    byItem: ListInsightsConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<InsightsConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.ListInsightsConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInsightsConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<InsightsConfig, Swift.Error> {
    let request = ListInsightsConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listInsightsConfigs(byItem: request)
  }

  public func createInsightsConfig(request: CreateInsightsConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInsightsConfig(request: request, options: .init())
  }

  public func createInsightsConfig(
    request: CreateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createInsightsConfig(withPolling: CreateInsightsConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<InsightsConfig>
  {
    try await self.createInsightsConfig(withPolling: withPolling, options: .init())
  }

  public func createInsightsConfig(
    withPolling: CreateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InsightsConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInsightsConfig(
    parent: Swift.String,
    insightsConfig: InsightsConfig?,
    insightsConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig> {
    let request = CreateInsightsConfigRequest().with {
      $0.parent = parent
      $0.insightsConfig = insightsConfig
      $0.insightsConfigId = insightsConfigId
    }
    return try await self.createInsightsConfig(withPolling: request)
  }

  public func getInsightsConfig(request: GetInsightsConfigRequest) async throws
    -> GoogleCloudDeveloperConnectV1.InsightsConfig
  {
    try await self.getInsightsConfig(request: request, options: .init())
  }

  public func getInsightsConfig(
    request: GetInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.InsightsConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getInsightsConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.InsightsConfig {
    let request = GetInsightsConfigRequest().with {
      $0.name = name
    }
    return try await self.getInsightsConfig(request: request)
  }

  public func updateInsightsConfig(request: UpdateInsightsConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInsightsConfig(request: request, options: .init())
  }

  public func updateInsightsConfig(
    request: UpdateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateInsightsConfig(withPolling: UpdateInsightsConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<InsightsConfig>
  {
    try await self.updateInsightsConfig(withPolling: withPolling, options: .init())
  }

  public func updateInsightsConfig(
    withPolling: UpdateInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<InsightsConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<InsightsConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInsightsConfig(request: DeleteInsightsConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInsightsConfig(request: request, options: .init())
  }

  public func deleteInsightsConfig(
    request: DeleteInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteInsightsConfig(withPolling: DeleteInsightsConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInsightsConfig(withPolling: withPolling, options: .init())
  }

  public func deleteInsightsConfig(
    withPolling: DeleteInsightsConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInsightsConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteInsightsConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteInsightsConfig(withPolling: request)
  }

  public func getDeploymentEvent(request: GetDeploymentEventRequest) async throws
    -> GoogleCloudDeveloperConnectV1.DeploymentEvent
  {
    try await self.getDeploymentEvent(request: request, options: .init())
  }

  public func getDeploymentEvent(
    request: GetDeploymentEventRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.DeploymentEvent {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDeploymentEvent(
    name: Swift.String,
  ) async throws -> GoogleCloudDeveloperConnectV1.DeploymentEvent {
    let request = GetDeploymentEventRequest().with {
      $0.name = name
    }
    return try await self.getDeploymentEvent(request: request)
  }

  public func listDeploymentEvents(request: ListDeploymentEventsRequest) async throws
    -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse
  {
    try await self.listDeploymentEvents(request: request, options: .init())
  }

  public func listDeploymentEvents(
    request: ListDeploymentEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDeploymentEvents(
    byItem: ListDeploymentEventsRequest
  ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error> {
    try self.listDeploymentEvents(byItem: byItem, options: .init())
  }

  public func listDeploymentEvents(
    byItem: ListDeploymentEventsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudDeveloperConnectV1.ListDeploymentEventsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDeploymentEvents(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DeploymentEvent, Swift.Error> {
    let request = ListDeploymentEventsRequest().with {
      $0.parent = parent
    }
    return try self.listDeploymentEvents(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
