// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// RuntimeConfig represents the runtimes where the application is
/// deployed.
public struct RuntimeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Immutable. The URI of the runtime configuration.
  /// For GKE, this is the cluster name.
  /// For Cloud Run, this is the service name.
  public var uri: Swift.String = Swift.String()

  /// Output only. The state of the Runtime.
  public var state: RuntimeConfig.State = RuntimeConfig.State()

  /// The type of the runtime.
  public var runtime: OneOf_Runtime? = nil

  /// Where the runtime is derived from.
  public var derivedFrom: OneOf_DerivedFrom? = nil

  /// Initialize a new instance of `RuntimeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeConfig().with { $0.gkeWorkload = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gkeWorkload = "gkeWorkload"
    case googleCloudRun = "googleCloudRun"
    case appHubWorkload = "appHubWorkload"
    case appHubService = "appHubService"
    case uri = "uri"
    case state = "state"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.uri = try container.decode(Swift.String.self, forKey: .uri)
    self.state = try container.decode(RuntimeConfig.State.self, forKey: .state)

    var runtime: OneOf_Runtime? = nil
    let runtimeCheckAndSet = {
      if runtime != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'runtime'"))
      }
      runtime = $0
    }
    if let gkeWorkload = try container.decodeIfPresent(GKEWorkload?.self, forKey: .gkeWorkload) {
      try runtimeCheckAndSet(.gkeWorkload(gkeWorkload))
    }
    if let googleCloudRun = try container.decodeIfPresent(
      GoogleCloudRun?.self, forKey: .googleCloudRun)
    {
      try runtimeCheckAndSet(.googleCloudRun(googleCloudRun))
    }
    self.runtime = runtime

    var derivedFrom: OneOf_DerivedFrom? = nil
    let derivedFromCheckAndSet = {
      if derivedFrom != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'derivedFrom'"))
      }
      derivedFrom = $0
    }
    if let appHubWorkload = try container.decodeIfPresent(
      AppHubWorkload?.self, forKey: .appHubWorkload)
    {
      try derivedFromCheckAndSet(.appHubWorkload(appHubWorkload))
    }
    if let appHubService = try container.decodeIfPresent(
      AppHubService?.self, forKey: .appHubService)
    {
      try derivedFromCheckAndSet(.appHubService(appHubService))
    }
    self.derivedFrom = derivedFrom
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.state, forKey: .state)

    if let choice = self.runtime {
      switch choice {
      case .gkeWorkload(let value):
        try container.encode(value, forKey: .gkeWorkload)
      case .googleCloudRun(let value):
        try container.encode(value, forKey: .googleCloudRun)
      }
    }

    if let choice = self.derivedFrom {
      switch choice {
      case .appHubWorkload(let value):
        try container.encode(value, forKey: .appHubWorkload)
      case .appHubService(let value):
        try container.encode(value, forKey: .appHubService)
      }
    }
  }

  /// The state of the runtime in the InsightsConfig.
  /// Whether the runtime is linked to the InsightsConfig.
  public enum State: Codable, Equatable, Sendable {
    /// No state specified.
    case unspecified
    /// The runtime configuration has been linked to the InsightsConfig.
    case linked
    /// The runtime configuration has been unlinked to the InsightsConfig.
    case unlinked
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .linked: return 1
      case .unlinked: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .linked: return "LINKED"
      case .unlinked: return "UNLINKED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "LINKED": self = .linked
      case "UNLINKED": self = .unlinked
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .linked
      case 2: self = .unlinked
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .linked: return try container.encode(1)
      case .unlinked: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type of the runtime.
  public enum OneOf_Runtime: Codable, Equatable, Sendable {
    /// Output only. Google Kubernetes Engine runtime.
    indirect case gkeWorkload(GKEWorkload?)
    /// Output only. Cloud Run runtime.
    indirect case googleCloudRun(GoogleCloudRun?)
  }

  /// Where the runtime is derived from.
  public enum OneOf_DerivedFrom: Codable, Equatable, Sendable {
    /// Output only. App Hub Workload.
    indirect case appHubWorkload(AppHubWorkload?)
    /// Output only. App Hub Service.
    indirect case appHubService(AppHubService?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.RuntimeConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
