// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Message for responding to starting an OAuth flow.
public struct StartOAuthResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The ticket to be used for post processing the callback from the service
  /// provider.
  public var ticket: Swift.String = Swift.String()

  /// Please refer to https://datatracker.ietf.org/doc/html/rfc7636#section-4.1
  public var codeChallenge: Swift.String = Swift.String()

  /// Please refer to https://datatracker.ietf.org/doc/html/rfc7636#section-4.2
  public var codeChallengeMethod: Swift.String = Swift.String()

  /// The client ID to the OAuth App of the service provider.
  public var clientId: Swift.String = Swift.String()

  /// The list of scopes requested by the application.
  public var scopes: [Swift.String] = []

  /// The authorization server URL to the OAuth flow of the service provider.
  public var authUri: Swift.String = Swift.String()

  /// The ID of the service provider.
  public var id: OneOf_Id? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StartOAuthResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StartOAuthResponse().with { $0.systemProviderId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let systemProviderId = CodingKeys(stringValue: "systemProviderId")
    static let ticket = CodingKeys(stringValue: "ticket")
    static let codeChallenge = CodingKeys(stringValue: "codeChallenge")
    static let codeChallengeMethod = CodingKeys(stringValue: "codeChallengeMethod")
    static let clientId = CodingKeys(stringValue: "clientId")
    static let scopes = CodingKeys(stringValue: "scopes")
    static let authUri = CodingKeys(stringValue: "authUri")

    static let _knownKeys: Set<Swift.String> = [
      "systemProviderId",
      "ticket",
      "codeChallenge",
      "codeChallengeMethod",
      "clientId",
      "scopes",
      "authUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ticket) {
      self.ticket = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .codeChallenge) {
      self.codeChallenge = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .codeChallengeMethod) {
      self.codeChallengeMethod = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
      self.clientId = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .scopes) {
      self.scopes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .authUri) {
      self.authUri = value
    }

    var id: OneOf_Id? = nil
    let idCheckAndSet = {
      if id != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'id'"))
      }
      id = $0
    }
    if let systemProviderId = try container.decodeIfPresent(
      SystemProvider.self, forKey: .systemProviderId)
    {
      try idCheckAndSet(.systemProviderId(systemProviderId))
    }
    self.id = id
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ticket, forKey: .ticket)
    try container.encode(self.codeChallenge, forKey: .codeChallenge)
    try container.encode(self.codeChallengeMethod, forKey: .codeChallengeMethod)
    try container.encode(self.clientId, forKey: .clientId)
    try container.encode(self.scopes, forKey: .scopes)
    try container.encode(self.authUri, forKey: .authUri)

    if let choice = self.id {
      switch choice {
      case .systemProviderId(let value):
        try container.encode(value, forKey: .systemProviderId)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The ID of the service provider.
  public enum OneOf_Id: Codable, Equatable, Sendable {
    /// The ID of the system provider.
    case systemProviderId(SystemProvider)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.StartOAuthResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
