// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request for updating an InsightsConfig.
public struct UpdateInsightsConfigRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource being updated.
  public var insightsConfig: InsightsConfig? = nil

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID so that if you must retry your request, the server will know to
  /// ignore the request if it has already been completed. The server will
  /// guarantee that for at least 60 minutes after the first request.
  ///
  /// For example, consider a situation where you make an initial request and the
  /// request times out. If you make the request again with the same request
  /// ID, the server can check if original operation with the same request ID
  /// was received, and if so, will ignore the second request. This prevents
  /// clients from accidentally creating duplicate commitments.
  ///
  /// The request ID must be a valid UUID with the exception that zero UUID is
  /// not supported (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Optional. If set to true, and the insightsConfig is not found a new
  /// insightsConfig will be created. In this situation `update_mask` is ignored.
  /// The creation will succeed only if the input insightsConfig has all the
  /// necessary information (e.g a github_config with both  user_oauth_token and
  /// installation_id properties).
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. If set, validate the request, but do not actually post it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateInsightsConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateInsightsConfigRequest().with { $0.insightsConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let insightsConfig = CodingKeys(stringValue: "insightsConfig")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let allowMissing = CodingKeys(stringValue: "allowMissing")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "insightsConfig",
      "requestId",
      "allowMissing",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.insightsConfig = try container.decodeIfPresent(
      InsightsConfig.self, forKey: .insightsConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowMissing) {
      self.allowMissing = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.insightsConfig, forKey: .insightsConfig)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.allowMissing, forKey: .allowMissing)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.UpdateInsightsConfigRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
