// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// User represents a user connected to the service providers through
/// a AccountConnector.
public struct User: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Resource name of the user, in the format
  /// `projects/*/locations/*/accountConnectors/*/users/*`.
  public var name: Swift.String = Swift.String()

  /// Output only. Developer Connect automatically converts user identity
  /// to some human readable description, e.g., email address.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The timestamp when the user was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when the token was last requested.
  public var lastTokenRequestTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `User`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = User().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.developerconnect.v1.User"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
